name: My First Github Action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: node -v
      - name: Build the project
        run: npm run build
      - name: setup finish
        run: echo "Alasss!"
