name: My First Github Action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    outputs:
      text: ${{ steps.setup_finish.outputs.text }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: node -v
      - name: Install node modules
        run: npm install
      - name: Build the project
        run: npm run build
      - name: setup finish
        id: setup_finish
        run: echo "::set-output name=text::hellow world from build job"

  test-app:
    needs: build-app
    env:
      MY_JOB_OUTPUT: ${{needs.build-app.outputs.text}}
    runs-on: ubuntu-latest
    steps:
      - run: echo $MY_JOB_OUTPUT
